DATA_LIST = {
  "PMPM": "pop'n music ピカピカポップ君モデル",
  "CARDCONNECT": "カードコネクト(白)",
  "CARDCONNECT_R": "カードコネクト(赤)",
  "MOMOTETSU_W_MEDAL": "桃太郎電鉄ワールド ～地球もメダルもまわってる！～",
  "COLORCOLOTTA7": "カラコロッタ トロピカルリゾート",
  "MFCU": "麻雀格闘倶楽部",
  "MFCU_HG": "麻雀格闘倶楽部(ﾊｲｸﾞﾚｰﾄﾞﾓﾃﾞﾙ)",
  "MFCU_STD": "麻雀格闘倶楽部(ｽﾀﾝﾀﾞｰﾄﾞﾓﾃﾞﾙ)",
  "MFCU_NEW": "麻雀格闘倶楽部(ﾆｭｰｷｬﾋﾞﾈｯﾄ機能搭載ﾓﾃﾞﾙ)",
  "QMA9": "クイズマジックアカデミー",
  "QMA_HG": "クイズマジックアカデミー（ハイグレードモデル）",
  "IIDX": "beatmania IIDX",
  "IIDX_LN": "beatmania IIDX LIGHTNING MODEL",
  "PANDORA2_MEDAL": "モンスター烈伝 オレカバトル2 パンドラのメダル",
  "GIWorldClassic3": "GI-WorldClassic GLORY",
  "GITADORADMA": "GITADORA DrumMania -ARENA MODEL-",
  "GITADORAGFA": "GITADORA GuitarFreaks -ARENA MODEL-",
  "GITADORADM": "GITADORA DrumMania",
  "GITADORAGF": "GITADORA GuitarFreaks",
  "PAWAPURO_MEDAL_TWO": "パワフルプロ野球 開幕メダルシリーズ！ 二刀流！",
  "ANIMAL8": "アニマロッタ 勇者アニマと竜の秘宝",
  "ORECABATTLE": "モンスター烈伝 オレカバトル2",
  "PCHARGER": "PASELIチャージ機",
  "PMSP": "pop'n music シリーズ",
  "PAWAPURO_MEDAL": "パワフルプロ野球 開幕メダルシリーズ！",
  "DDR20TH": "DanceDanceRevolution 20th anniversary model",
  "DDR": "DanceDanceRevolution",
  "PLRS": "ポラリスコード",
  "COLORCOLOTTA6": "カラコロッタ まぼろしの桃源郷",
  "EKEC3": "エルドラクラウン 悠久のラビリンス",
  "FTRI5": "フォーチュントリニティ 時空のダイヤモンド",
  "JUBEAT": "jubeat",
  "MOMOTETSU_MEDAL": "桃太郎電鉄 ～メダルゲームも定番！～",
  "MFG": "麻雀ファイトガール",
  "MFG_HG": "麻雀ファイトガール(ﾊｲｸﾞﾚｰﾄﾞﾓﾃﾞﾙ)",
  "ANIMAL7": "アニマロッタ 夢のアニマランド",
  "CCJ": "チェイスチェイスジョーカーズ",
  "BOMBERGIRL": "ボンバーガール",
  "COLORCOLOTTA5": "カラコロッタ フローズンアイランド",
  "QKS": "QuizKnock STADIUM",
  "DANCEAROUND": "DANCE aROUND",
  "GRANDCROSS_GOLD": "GRANDCROSS GOLD",
  "GIWorldClassic2": "GI-WorldClassic RISING",
  "GIWorldClassic2_VRDX": "GI-WorldClassic RISING(DXタイプ)",
  "DD": "DUEL DREAM",
  "ANIMAL6": "アニマロッタ アニマと星の物語",
  "SDVX_VM": "SOUND VOLTEX -Valkyrie model-",
  "SDVX": "SOUND VOLTEX",
  "BUSOUSHINKI": "武装神姫",
  "FTRI4": "FORTUNE TRINITY 精霊の至宝祭",
  "SMASTA": "スマッシュスタジアム",
  "COLORCOLOTTA4": "カラコロッタ めざせ！夢の宝島",
  "NOSTALGIA": "ノスタルジア",
  "FEATUREPREMIUM": "FEATURE Premium シリーズ",
  "ANIMAL5": "アニマロッタ アニマと雲の大樹",
  "GRANDCROSS_LEGEND": "GRANDCROSS LEGEND",
  "BOMBER_MEDAL": "ボンバーマン・ザ・メダル",
  "BBCH": "ビシバシチャンネル",
  "TSUNAGALOTTA2": "ツナガロッタ アニマと虹色の秘境",
  "DAN": "DANCERUSH STARDOM",
  "MARBLEFEVER": "マーブルフィーバー",
  "GIWorldClassic": "GI-WorldClassic",
  "GIWorldClassic_VR_DX": "GI-WorldClassic(DXタイプ)",
  "GIWorldClassic_VR_SD": "GI-WorldClassic(STDタイプ)",
  "ANIMAL4": "おとぎの国のアニマ",
  "FTRI3": "フォーチュントリニティ3",
  "REFLECC": "REFLEC BEAT",
  "MUSECA": "MUSECA",
  "COLORCOLOTTA2": "カラコロッタ2",
  "GIVROAD": "GI-VICTORY ROAD",
  "GIVROAD_DX": "GI-VICTORY ROAD(DXタイプ)",
  "GIVROAD_STD": "GI-VICTORY ROAD(STDタイプ)",
  "ANIMAL3": "アニマロッタ3",
  "COLORCOLOTTA": "カラコロッタ",
  "ORECA_PANDORA": "オレカバトル パンドラのメダル",
  "WEAC2014ALL": "Winning Eleven AC 2014",
  "WEAC2014WIDE": "Winning Eleven AC 2014(新筺体)",
  "WEAC2014STD": "Winning Eleven AC 2014(ｽﾀﾝﾀﾞｰﾄﾞ筺体)",
  "dreamsphere": "DreamSphere GRANDCROSS",
  "SC1": "Steel Chronicle VICTROOPERS",
  "ANIMAL2": "アニマロッタ2",
  "GIGD": "GI-GranDesire",
  "FTRI2": "フォーチュントリニティ2",
  "SPINFEVER3": "SPINFEVER 夢幻のオーケストラ",
  "METEOSPARK": "ＭＥＴＥＯＳＰＡＲＫ",
  "WONDERMARCH": "WONDERMARCH",
  "DANEVOAC": "DanceEvolution ARCADE",
  "VENUSFOUNTAIN": "Venus Fountain",
  "SHOGI2": "天下一将棋会2",
  "GIHPJM": "GI-HORSEPARK JUDGMENT",
  "GIHPJM_STD": "GI-HORSEPARK JUDGMENT STD",
  "GCC": "グランドクロス クロニクル",
  "GITTV": "GI-Turf TV",
  "FTRI": "フォーチュントリニティ",
  "IRINGS": "Infinity Rings",
  "MILLIONET": "MILLIONET",
  "CVM": "悪魔城ドラキュラ THE MEDAL",
  "FF3": "FantasicFever3 Twinkle Fairytale",
  "TD": "トゥインクルドロップ",
  "PANIC": "PanicPirates",
  "GITW3": "GI-TURF WILD3",
  "GIHPGX": "GI-HORSEPARK GX",
  "GIHPGX_STD": "GI-HORSEPARK GX STD",
  "SPINFEVER2": "SPIN FEVER2",
  "GCP": "GRANDCROSS PREMIUM"
}
