name: Daily Scrape

permissions:
  contents: write

on:
  schedule:
    - cron: "0 0 1 * *" # 毎月1日の午前0時に実行
  # 手動実行
  workflow_dispatch:


jobs:
  build:
      runs-on: ubuntu-latest # 最新のubuntu環境で下記のジョブを実行

      steps:
        - uses: actions/checkout@v5

        - name: Install uv
          uses: astral-sh/setup-uv@v5

        - name: Install the project
          run: uv sync --locked --all-extras --dev

        - name: Run script
          run: |
            uv run playwright install
            uv run playwright install-deps
            uv run main.py


        - name: Commit and push
          run: |
            git config --global user.name "GitHub Actions"
            git config --global user.email "actions@github.com"
            git checkout -b new-shop-data
            git add shop_data.json
            git commit -m "Update shop data"
            git push origin new-shop-data
      